logging:
  config: classpath:logback-dev.xml
server:
  servlet:
    context-path: /ws-administrator
  port: ${PORT:0}
spring:
 config:
    import: auth-conf-dev.yml,eureka-conf-dev.yml,rabbitLoggerFilter-dev.yml
 datasource:
    password: ENC(wFOpcZpk+NQH+SwhSm+8Qh6408JBevVDAolGoc1ktomittZhsoL0CriR+zhRawUxBY/0xJiJg9d2zhowjLXnEupWkpXqKy9vF62gsOeKYQU=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(ATn9LtKbnnSGebs2Z1syfRmRQHCj4ZtRyuWrJUotgH7qZD5Mi1G1TueUbIF7dVvsADReVG8ezMNIjt8v7STOeQ==)
    url: ${BD_URL:ENC(npJEoO4bNId6lSlZxZ3bFxSuNaj3FzjyT3LMJU4h6v/le6ZFdBUPvWMQOLc15kKprut/fF9MCgY0bu/Q+W3Ar+v1N+BHFs21UfclJLnEpFtEujMf+tojcc6fv79tcPX7)}
    hikari:
      maximum-pool-size: 5
 jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
 cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: ENC(SB35wzleWcSKpy7Fl7+xGFwbbakNJyeVddL9AvkAHuvy2Y3gDvSlDuFkB8TvLnHFl8jfyv+5ysN4jX/aD1jgyEk+vtjCeTEl0Aj/fn19364QyrutUueIcyQlg6lmcon9)
            username: ENC(foINhruZ9GaXhnYU44uo55//vIsCb8eyLkmP17S7qxLxyCuEPSYFf6dHBQ0gdWIJ)
            password: ENC(gxuN6FjDneJ1YopqgxldRZ84vhT81rfyunMyWbNYL1AzwM0b/uZlALRDHMfK6wnIkZYLdHxTaPn/t7UGzhFqkQ==)
management:
#  server:
#    base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  endpoints:
    web:
#      base-path: ${server.servlet.context-path}/actuator
      exposure:
        include: '*'     
