logging:
  config: classpath:logback-dev.xml
server:
  servlet:
    context-path: /ws-admin-server
  port: ${PORT:8094}
management:
#  server:
#    base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  endpoints:
    web:
#      base-path: ${server.servlet.context-path}/actuator
      exposure:
        include: '*'
spring:
 config:
   import: eureka-conf-dev.yml
 datasource:
   password: ENC(2KDnq5WyTuO9tWVs/U3l2yzRqDrG6c9B1eS+CQcdo4a1DFfXc71rdwXf/QBqJ5BnfZxeMgbw7MBqitnlIGgbZ2NJ4aZb36lXVefzHyI3B+M=)
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: ENC(TTVBGypS2cXId/I4K7vJA1w7CN987/SUYSX6iRYPe2821fUtW0OnhLAhlPRaulvQmMvMUrwnEYPqxvkNzVs0MQ==)
   url: ${BD_URL:ENC(sZ/C++k57YTYOgxjRxs2iukcoO+KbE9oTbSGMPOrWff/54g3lFsBkqs4XLbs9EBFpra/UyKD97OwZCC6KArPalEJGkSX0L0bVY1eKLlM/HWC96LAmB/EHWnDoZ21ewCl)}
   hikari:
      maximum-pool-size: 5
 jpa:
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
