server:
  servlet:
    context-path: /ws-email
  port: ${PORT:0}
spring:
 config:
    import: auth-conf-dev.yml,eureka-conf-dev.yml,rabbitLoggerFilter-dev.yml    
 cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: ENC(SB35wzleWcSKpy7Fl7+xGFwbbakNJyeVddL9AvkAHuvy2Y3gDvSlDuFkB8TvLnHFl8jfyv+5ysN4jX/aD1jgyEk+vtjCeTEl0Aj/fn19364QyrutUueIcyQlg6lmcon9)
            username: ENC(foINhruZ9GaXhnYU44uo55//vIsCb8eyLkmP17S7qxLxyCuEPSYFf6dHBQ0gdWIJ)
            password: ENC(gxuN6FjDneJ1YopqgxldRZ84vhT81rfyunMyWbNYL1AzwM0b/uZlALRDHMfK6wnIkZYLdHxTaPn/t7UGzhFqkQ==)
 mail:
    host: ENC(wMsALFmW8GeobGnjCKK0SIV4Eg7Wb4kBhjehRTvwQPOIXvDQ0ROM071XvgZpctUHa2pxLXgVW+Ja9x+dfXExw4Exs3OiEnY1CfkAkQ0rb64=)
    sender: ENC(fPC21qQOZVpHTLPpNZovUYXpiHuT/ZyhgUo2vF2fZmCkYzQQ/AC+CroFUKkyveteV7aPpHofQanrA18kd3FSBw==)
    username: ENC(15DYRrVLA3Shj1ESifkEQiUGlm4X3q2z/tSHYrCGH9FvpIziEJRWwWwPMiBHvZVK7uz+AL15AVaxyqgMXOxqyw==)
    password: ENC(jIB+Yo4OZ8UzF9ypHezFMFxVm3Z7WtMZhELCG1pDVwFhwRevtk0nyEA2Wr4DlBiPJJ2fGG7wu2OHxGk9LP25sfQHAAR5XvduOu6Q/2MVTqo=)   
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
          port: '587'
        transport:
          protocol: smtp  
aws:
  bucketName: ENC(q/usequqYkCHn1WLdnpDHAq+Mc/C+KEN6QPoFy/JhQio8BFiSDYLmNJhJIbJuwJQ)
  fileName: email-templates/confirmation_signing_up.html  
  secretKey: ENC(UeilO9981x5O8ARbSIhz1RKAjOjfqieAeeCy7aQcIThEDq434LQ38SFnAE0zglLXcCTRNO6C26PPlBCJnnjFgn1rhaWcp5oKbZH59w0DeI8=)
  accessKey: ENC(739iffjzfm2Zsh8gTy7ltaBbZX2g9HhRGCrcMtAJLpSQbDv+kEtEA3UKEaMZ/bq8UhJK0wtYtMHhAo/VCJbPLg==)          
management:
#  server:
#    base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  endpoints:
    web:
#      base-path: ${server.servlet.context-path}/actuator
      exposure:
        include: '*' 
