server:
  servlet:
    context-path: /ws-sms
  port: ${PORT:0}
spring:
 config:
    import: auth-conf-dev.yml,eureka-conf-dev.yml,rabbitLoggerFilter-dev.yml
 cloud:
    openfeign:
      client:
        config:
         default:
            loggerLevel: full
         wsAuthenticator:
            url: ENC(SB35wzleWcSKpy7Fl7+xGFwbbakNJyeVddL9AvkAHuvy2Y3gDvSlDuFkB8TvLnHFl8jfyv+5ysN4jX/aD1jgyEk+vtjCeTEl0Aj/fn19364QyrutUueIcyQlg6lmcon9)
            username: ENC(foINhruZ9GaXhnYU44uo55//vIsCb8eyLkmP17S7qxLxyCuEPSYFf6dHBQ0gdWIJ)
            password: ENC(gxuN6FjDneJ1YopqgxldRZ84vhT81rfyunMyWbNYL1AzwM0b/uZlALRDHMfK6wnIkZYLdHxTaPn/t7UGzhFqkQ==)
sns:
 accessKey: ENC(gAeL7E9KkNFAa+yBxcyaDC7wAfYmyVmvzijANXyaY1luOXoFN2irXmfN5NBSC8hp+vQ4Ah723dVSBQBdEFeLEw==)
 secretKey: ENC(B4ITsO9SRP/6lBaz3PQgkBT5eiT5R2mSiUAbrvZVos+o5mn3vOJ2l/H+obJXTEDct3SmqczAfK1lBzY53DcjVNnlyk3sLk3Zn/2RinQ5gRM=)            
management:
#  server:
#    base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true   
  endpoints:
    web:
#      base-path: ${server.servlet.context-path}/actuator
      exposure:
        include: '*'
